apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisdom-server-deployment
  labels:
    app: wisdom-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisdom-server
  template:
    metadata:
      labels:
        app: wisdom-server
    spec:
      containers:
      - name: wisdom-server
        image: registry2002/wisdom-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4499
        readinessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: wisdom-server-service
  labels:
    app: wisdom-server
spec:
  type: LoadBalancer
  selector:
    app: wisdom-server
  ports:
    - name: http
      port: 80          # External port
      targetPort: 4499  # Container port
